// src/palette.ts
import type { ColorSwatch, PaletteGroup } from './types';

export const IDEAS_PALETTE: PaletteGroup = {
  deep: [
    { name: '딥 오렌지',   hex: '#C19025' },
    { name: '딥 레드',     hex: '#A83232' },
    { name: '딥 핑크',     hex: '#C14878' },
    { name: '딥 바이올렛', hex: '#7C3D8A' },
    { name: '딥 퍼플',     hex: '#4A3580' },
    { name: '딥 블루',     hex: '#1E3F82' },
    { name: '딥 민트',     hex: '#1A6E6A' },
    { name: '딥 그린',     hex: '#2A5C30' },
    { name: '딥 라임',     hex: '#4A7010' },
    { name: '딥 카키',     hex: '#5C4E20' },
    { name: '딥 레몬',     hex: '#8A7A10' },
    { name: '딥 옐로우',   hex: '#A88A10' },
    { name: '딥 브라운',   hex: '#6B3A1A' },
  ],
  vivid: [
    { name: '비비드 오렌지',   hex: '#FF6B00' },
    { name: '비비드 레드',     hex: '#FF2020' },
    { name: '비비드 핑크',     hex: '#FF3D8A' },
    { name: '비비드 바이올렛', hex: '#C040D8' },
    { name: '비비드 퍼플',     hex: '#7040E8' },
    { name: '비비드 블루',     hex: '#1C60FF' },
    { name: '비비드 민트',     hex: '#00C8A0' },
    { name: '비비드 그린',     hex: '#20A840' },
    { name: '비비드 라임',     hex: '#80D000' },
    { name: '비비드 카키',     hex: '#8A9020' },
    { name: '비비드 레몬',     hex: '#F0D800' },
    { name: '비비드 옐로우',   hex: '#FFD010' },
    { name: '비비드 브라운',   hex: '#C06020' },
  ],
  light: [
    { name: '라이트 오렌지',   hex: '#FFD8A8' },
    { name: '라이트 레드',     hex: '#FFB0A0' },
    { name: '라이트 핑크',     hex: '#FFC0D8' },
    { name: '라이트 바이올렛', hex: '#D8B8F8' },
    { name: '라이트 퍼플',     hex: '#C8C0F8' },
    { name: '라이트 블루',     hex: '#A8D8F8' },
    { name: '라이트 민트',     hex: '#A0E8D8' },
    { name: '라이트 그린',     hex: '#B8E8B8' },
    { name: '라이트 라임',     hex: '#D0F0A0' },
    { name: '라이트 카키',     hex: '#D8D8A8' },
    { name: '라이트 레몬',     hex: '#F8F0A0' },
    { name: '라이트 옐로우',   hex: '#FFF0B0' },
    { name: '라이트 브라운',   hex: '#E8D0B8' },
  ],
  pastel: [
    { name: '파스텔 오렌지',   hex: '#FFE8CC' },
    { name: '파스텔 레드',     hex: '#FFD8D0' },
    { name: '파스텔 핑크',     hex: '#FFD8E8' },
    { name: '파스텔 바이올렛', hex: '#ECD8F8' },
    { name: '파스텔 퍼플',     hex: '#E4E0F8' },
    { name: '파스텔 블루',     hex: '#D4ECF8' },
    { name: '파스텔 민트',     hex: '#D0F4EC' },
    { name: '파스텔 그린',     hex: '#D8F0D8' },
    { name: '파스텔 라임',     hex: '#E8F8D0' },
    { name: '파스텔 카키',     hex: '#ECEDD8' },
    { name: '파스텔 레몬',     hex: '#F8F8D8' },
    { name: '파스텔 옐로우',   hex: '#FFF8DC' },
    { name: '파스텔 브라운',   hex: '#F4E8DC' },
  ],
};
